version: '3'
networks:
  ping:
    name: ping
services:
  ping-bot:
    container_name: pingBot
    image: ping-bot
    build: ./bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_ID=${ADMIN_ID}
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
    networks:
      - ping
    depends_on:
      - db
    restart: always
  ping-script:
    container_name: pingScript
    image: ping-script
    build: ./routerping
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    networks:
      - ping
    depends_on:
      - db
    restart: always
  db:
    image: mongo:4
    container_name: mongoPing
    volumes:
      - ./mongo:/data/db
    networks:
      - ping
    restart: always

